=== dwiilhammaulana/Project_UMKM_Solusion/.dart-home/Local/Pub/Cache/hosted/pub.dev/record_use-0.6.0/doc/schema/record_use.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/RecordedUses",
  "definitions": {
    "Call": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "anyOf": [
            {
              "enum": [
                "tearoff",
                "with_arguments"
              ]
            },
            {
              "type": "string"
            }
          ]
        },
        "loading_unit_index": {
          "type": "integer"
        },
        "receiver": {
          "type": [
            "integer",
            "null"
          ]
        }
      },
      "required": [
        "loading_unit_index",
        "type"
      ],
      "if": {
        "properties": {
          "type": {
            "const": "with_arguments"
          }
        }
      },
      "then": {
        "properties": {
          "named": {
            "type": "object",
            "additionalProperties": {
              "type": "integer"
            }
          },
          "positional": {
            "type": "array",
            "items": {
              "type": "integer"
            }
          }
        }
      }
    },
    "CallRecording": {
      "type": "object",
      "properties": {
        "definition_index": {
          "type": "integer"
        },
        "uses": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Call"
          },
          "minItems": 1
        }
      },
      "required": [
        "definition_index",
        "uses"
      ],
      "additionalProperties": false
    },
    "Constant": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "anyOf": [
            {
              "enum": [
                "bool",
                "double",
                "enum",
                "instance",
                "int",
                "list",
                "map",
                "non_constant",
                "null",
                "record",
                "set",
                "string",
                "symbol",
                "unsupported"
              ]
            },
            {
              "type": "string"
            }
          ]
        }
      },
      "required": [
        "type"
      ],
      "allOf": [
        {
          "if": {
            "properties": {
              "type": {
                "const": "bool"
              }
            }
          },
          "then": {
            "properties": {
              "value": {
                "type": "boolean"
              }
            },
            "required": [
              "value"
            ]
          }
        },
        {
          "if": {
            "properties": {
              "type": {
                "const": "double"
              }
            }
          },
          "then": {
            "properties": {
              "value": {
                "$ref": "#/definitions/DoubleConstantValue"
              }
            },
            "required": [
              "value"
            ]
          }
        },
        {
          "if": {
            "properties": {
              "type": {
                "const": "enum"
              }
            }
          },
          "then": {
            "properties": {
              "definition_index": {
                "type": "integer"
              },
              "index": {
                "type": "integer"
              },
              "name": {
                "type": "string"
              },
              "value": {
                "type": "object",
                "additionalProperties": {
                  "type": "integer"
                }
              }
            },
            "required": [
              "definition_index",
              "index",
              "name"
            ]
          }
        },
        {
          "if": {
            "properties": {
              "type": {
                "const": "instance"
              }
            }
          },
          "then": {
            "properties": {
              "definition_index": {
                "type": "integer"
              },
              "value": {
                "type": "object",
                "additionalProperties": true
              }
            },
            "required": [
              "definition_index"
            ]
          }
        },
        {
          "if": {
            "properties": {
              "type": {
                "const": "int"
              }
            }
          },
          "then": {
            "properties": {
              "value": {
                "type": "integer"
              }
            },
            "required": [
              "value"
            ]
          }
        },
        {
          "if": {
            "properties": {
              "type": {
                "const": "list"
              }
            }
          },
          "then": {
            "properties": {
              "value": {
                "type": "array",
                "items": {
                  "type": "integer"
                }
              }
            },
            "required": [
              "value"
            ]
          }
        },
        {
          "if": {
            "properties": {
              "type": {
                "const": "map"
              }
            }
          },
          "then": {
            "properties": {
              "value": {
                "type": "array",
                "items": {
                  "$ref": "#/definitions/MapEntry"
                }
              }
            },
            "required": [
              "value"
            ]
          }
        },
        {
          "if": {
            "properties": {
              "type": {
                "const": "non_constant"
              }
            }
          },
          "then": {
            "not": {
              "required": [
                "value"
              ]
            }
          }
        },
        {
          "if": {
            "properties": {
              "type": {
                "const": "null"
              }
            }
          },
          "then": {
            "not": {
              "required": [
                "value"
              ]
            }
          }
        },
        {
          "if": {
            "properties": {
              "type": {
                "const": "record"
              }
            }
          },
          "then": {
            "properties": {
              "named": {
                "type": "object",
                "additionalProperties": {
                  "type": "integer"
                }
              },
              "positional": {
                "type": "array",
                "items": {
                  "type": "integer"
                }
              }
            }
          }
        },
        {
          "if": {
            "properties": {
              "type": {
                "const": "set"
              }
            }
          },
          "then": {
            "properties": {
              "value": {
                "type": "array",
                "items": {
                  "type": "integer"
                }
              }
            },
            "required": [
              "value"
            ]
          }
        },
        {
          "if": {
            "properties": {
              "type": {
                "const": "string"
              }
            }
          },
          "then": {
            "properties": {
              "value": {
                "type": "string"
              }
            },
            "required": [
              "value"
            ]
          }
        },
        {
          "if": {
            "properties": {
              "type": {
                "const": "symbol"
              }
            }
          },
          "then": {
            "properties": {
              "libraryUri": {
                "type": [
                  "null",
                  "string"
                ],
                "pattern": "^package:"
              },
              "name": {
                "type": "string"
              }
            },
            "required": [
              "name"
            ]
          }
        },
        {
          "if": {
            "properties": {
              "type": {
                "const": "unsupported"
              }
            }
          },
          "then": {
            "properties": {
              "message": {
                "type": "string"
              }
            },
            "required": [
              "message"
            ]
          }
        }
      ]
    },
    "Definition": {
      "type": "object",
      "properties": {
        "path": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Name"
          },
          "minItems": 1
        },
        "uri": {
          "type": "string",
          "pattern": "^package:"
        }
      },
      "required": [
        "path",
        "uri"
      ]
    },
    "DoubleConstantValue": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "anyOf": [
            {
              "enum": [
                "negative_infinity",
                "not_a_number",
                "number",
                "positive_infinity"
              ]
            },
            {
              "type": "string"
            }
          ]
        },
        "value": {
          "type": "number"
        }
      },
      "required": [
        "type"
      ],
      "allOf": [
        {
          "if": {
            "properties": {
              "type": {
                "const": "number"
              }
            }
          },
          "then": {
            "required": [
              "value"
            ]
          }
        }
      ]
    },
    "Instance": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "anyOf": [
            {
              "enum": [
                "constant",
                "creation",
                "tearoff"
              ]
            },
            {
              "type": "string"
            }
          ]
        },
        "loading_unit_index": {
          "type": "integer"
        }
      },
      "required": [
        "loading_unit_index",
        "type"
      ],
      "allOf": [
        {
          "if": {
            "properties": {
              "type": {
                "const": "constant"
              }
            }
          },
          "then": {
            "properties": {
              "constant_index": {
                "type": "integer"
              }
            },
            "required": [
              "constant_index"
            ]
          }
        },
        {
          "if": {
            "properties": {
              "type": {
                "const": "creation"
              }
            }
          },
          "then": {
            "properties": {
              "definition_index": {
                "type": "integer"
              },
              "named": {
                "type": "object",
                "additionalProperties": {
                  "type": "integer"
                }
              },
              "positional": {
                "type": "array",
                "items": {
                  "type": "integer"
                }
              }
            },
            "required": [
              "definition_index"
            ]
          }
        },
        {
          "if": {
            "properties": {
              "type": {
                "const": "tearoff"
              }
            }
          },
          "then": {
            "properties": {
              "definition_index": {
                "type": "integer"
              }
            },
            "required": [
              "definition_index"
            ]
          }
        }
      ]
    },
    "InstanceRecording": {
      "type": "object",
      "properties": {
        "definition_index": {
          "type": "integer"
        },
        "uses": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Instance"
          },
          "minItems": 1
        }
      },
      "required": [
        "definition_index",
        "uses"
      ],
      "additionalProperties": false
    },
    "LoadingUnit": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        }
      },
      "required": [
        "name"
      ]
    },
    "MapEntry": {
      "type": "object",
      "properties": {
        "key": {
          "type": "integer"
        },
        "value": {
          "type": "integer"
        }
      },
      "required": [
        "key",
        "value"
      ]
    },
    "Name": {
      "type": "object",
      "properties": {
        "disambiguators": {
          "type": "array",
          "items": {
            "type": "string",
            "anyOf": [
              {
                "enum": [
                  "instance",
                  "static"
                ]
              },
              {
                "type": "string"
              }
            ]
          }
        },
        "kind": {
          "type": "string",
          "anyOf": [
            {
              "enum": [
                "class",
                "constructor",
                "enum",
                "extension",
                "extension_type",
                "getter",
                "method",
                "mixin",
                "operator",
                "setter"
              ]
            },
            {
              "type": "string"
            }
          ]
        },
        "name": {
          "type": "string"
        }
      },
      "required": [
        "kind",
        "name"
      ]
    },
    "RecordedUses": {
      "type": "object",
      "properties": {
        "definitions": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Definition"
          }
        },
        "constants": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Constant"
          }
        },
        "loading_units": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/LoadingUnit"
          }
        },
        "uses": {
          "$ref": "#/definitions/Uses"
        }
      }
    },
    "Uses": {
      "type": "object",
      "properties": {
        "instances": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/InstanceRecording"
          }
        },
        "static_calls": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/CallRecording"
          }
        }
      },
      "additionalProperties": false
    }
  }
}

=== dwiilhammaulana/Project_UMKM_Solusion/.dart-home/Local/Pub/Cache/hosted/pub.dev/record_use-0.6.0/test_data/json/top_level_method.json
{
  "$schema": "../../doc/schema/record_use.schema.json",
  "constants": [
    {
      "type": "int",
      "value": 42
    }
  ],
  "definitions": [
    {
      "path": [
        {
          "disambiguators": [
            "static"
          ],
          "kind": "method",
          "name": "someTopLevelMethod"
        }
      ],
      "uri": "package:record_use_test/top_level_method.dart"
    }
  ],
  "loading_units": [
    {
      "name": "1"
    }
  ],
  "uses": {
    "static_calls": [
      {
        "definition_index": 0,
        "uses": [
          {
            "loading_unit_index": 0,
            "positional": [
              0
            ],
            "type": "with_arguments"
          }
        ]
      }
    ]
  }
}

=== dwiilhammaulana/Project_UMKM_Solusion/.dart-home/Local/Pub/Cache/hosted/pub.dev/record_use-0.6.0/test_data/json/map_complex_keys.json
{
  "$schema": "../../doc/schema/record_use.schema.json",
  "constants": [
    {
      "type": "bool",
      "value": true
    },
    {
      "type": "int",
      "value": 1
    },
    {
      "type": "string",
      "value": "bool-key"
    },
    {
      "type": "string",
      "value": "int-key"
    },
    {
      "type": "map",
      "value": [
        {
          "key": 0,
          "value": 2
        },
        {
          "key": 1,
          "value": 3
        }
      ]
    }
  ],
  "definitions": [
    {
      "path": [
        {
          "kind": "class",
          "name": "SomeClass"
        },
        {
          "disambiguators": [
            "static"
          ],
          "kind": "method",
          "name": "someStaticMethod"
        }
      ],
      "uri": "package:record_use_test/map_complex_keys.dart"
    }
  ],
  "loading_units": [
    {
      "name": "1"
    }
  ],
  "uses": {
    "static_calls": [
      {
        "definition_index": 0,
        "uses": [
          {
            "loading_unit_index": 0,
            "positional": [
              4
            ],
            "type": "with_arguments"
          }
        ]
      }
    ]
  }
}

=== dwiilhammaulana/Project_UMKM_Solusion/.dart-home/Local/Pub/Cache/hosted/pub.dev/record_use-0.6.0/test_data/json/recorded_uses_v2.json
{
  "$schema": "../../doc/schema/record_use.schema.json",
  "constants": [
    {
      "type": "null"
    },
    {
      "type": "bool",
      "value": false
    },
    {
      "type": "int",
      "value": 0
    },
    {
      "type": "int",
      "value": 1
    },
    {
      "type": "int",
      "value": 42
    },
    {
      "type": "int",
      "value": 99
    },
    {
      "type": "string",
      "value": "camus"
    },
    {
      "type": "string",
      "value": "einstein"
    },
    {
      "type": "string",
      "value": "insert"
    },
    {
      "type": "string",
      "value": "jenkins"
    },
    {
      "type": "string",
      "value": "key"
    },
    {
      "type": "string",
      "value": "lib_SHA1"
    },
    {
      "type": "string",
      "value": "mercury"
    },
    {
      "definition_index": 0,
      "type": "instance"
    },
    {
      "type": "list",
      "value": [
        7,
        8,
        1
      ]
    },
    {
      "type": "map",
      "value": [
        {
          "key": 10,
          "value": 5
        }
      ]
    },
    {
      "definition_index": 2,
      "index": 0,
      "name": "val1",
      "type": "enum",
      "value": {
        "a": 4
      }
    },
    {
      "definition_index": 0,
      "type": "instance",
      "value": {
        "a": 4,
        "b": 0
      }
    },
    {
      "type": "list",
      "value": [
        6,
        14,
        7
      ]
    }
  ],
  "definitions": [
    {
      "path": [
        {
          "kind": "class",
          "name": "MyAnnotation"
        }
      ],
      "uri": "package:js_runtime/js_helper.dart"
    },
    {
      "path": [
        {
          "kind": "class",
          "name": "MyClass"
        },
        {
          "disambiguators": [
            "static"
          ],
          "kind": "getter",
          "name": "loadDeferredLibrary"
        }
      ],
      "uri": "package:js_runtime/js_helper.dart"
    },
    {
      "path": [
        {
          "kind": "enum",
          "name": "MyEnum"
        }
      ],
      "uri": "package:js_runtime/js_helper.dart"
    }
  ],
  "loading_units": [
    {
      "name": "3"
    },
    {
      "name": "o.js"
    }
  ],
  "uses": {
    "instances": [
      {
        "definition_index": 0,
        "uses": [
          {
            "constant_index": 13,
            "loading_unit_index": 0,
            "type": "constant"
          },
          {
            "constant_index": 17,
            "loading_unit_index": 0,
            "type": "constant"
          }
        ]
      },
      {
        "definition_index": 2,
        "uses": [
          {
            "constant_index": 16,
            "loading_unit_index": 0,
            "type": "constant"
          }
        ]
      }
    ],
    "static_calls": [
      {
        "definition_index": 1,
        "uses": [
          {
            "loading_unit_index": 1,
            "named": {
              "freddy": 12,
              "leroy": 9
            },
            "positional": [
              11,
              1,
              3
            ],
            "type": "with_arguments"
          },
          {
            "loading_unit_index": 1,
            "named": {
              "freddy": 2,
              "leroy": 9
            },
            "positional": [
              11,
              15,
              18
            ],
            "type": "with_arguments"
          }
        ]
      }
    ]
  }
}

=== dwiilhammaulana/Project_UMKM_Solusion/.dart-home/Local/Pub/Cache/hosted/pub.dev/record_use-0.6.0/test_data/json/named_with_function_arg.json
{
  "$schema": "../../doc/schema/record_use.schema.json",
  "constants": [
    {
      "type": "non_constant"
    },
    {
      "type": "string",
      "value": "hello-world"
    }
  ],
  "definitions": [
    {
      "path": [
        {
          "disambiguators": [
            "static"
          ],
          "kind": "method",
          "name": "Ext|foo"
        }
      ],
      "uri": "package:record_use_test/named_with_function_arg.dart"
    }
  ],
  "loading_units": [
    {
      "name": "1"
    }
  ],
  "uses": {
    "static_calls": [
      {
        "definition_index": 0,
        "uses": [
          {
            "loading_unit_index": 0,
            "named": {
              "s": 1
            },
            "positional": [
              0
            ],
            "type": "with_arguments"
          }
        ]
      }
    ]
  }
}

=== dwiilhammaulana/Project_UMKM_Solusion/.dart-home/Local/Pub/Cache/hosted/pub.dev/record_use-0.6.0/test_data/json/record_enum.json
{
  "$schema": "../../doc/schema/record_use.schema.json",
  "constants": [
    {
      "type": "int",
      "value": 0
    },
    {
      "type": "string",
      "value": "a"
    },
    {
      "definition_index": 0,
      "type": "instance",
      "value": {
        "_name": 1,
        "index": 0
      }
    },
    {
      "definition_index": 0,
      "type": "instance",
      "value": {
        "a": 2
      }
    }
  ],
  "definitions": [
    {
      "path": [
        {
          "kind": "class",
          "name": "MyClass"
        }
      ],
      "uri": "package:record_use_test/record_enum.dart"
    }
  ],
  "loading_units": [
    {
      "name": "1"
    }
  ],
  "uses": {
    "instances": [
      {
        "definition_index": 0,
        "uses": [
          {
            "constant_index": 3,
            "loading_unit_index": 0,
            "type": "constant"
          }
        ]
      }
    ]
  }
}

=== dwiilhammaulana/Project_UMKM_Solusion/.dart-home/Local/Pub/Cache/hosted/pub.dev/record_use-0.6.0/test_data/json/instance_not_annotation.json
{
  "$schema": "../../doc/schema/record_use.schema.json",
  "constants": [
    {
      "definition_index": 0,
      "type": "instance"
    }
  ],
  "definitions": [
    {
      "path": [
        {
          "kind": "class",
          "name": "MyClass"
        }
      ],
      "uri": "package:record_use_test/instance_not_annotation.dart"
    }
  ],
  "loading_units": [
    {
      "name": "1"
    }
  ],
  "uses": {
    "instances": [
      {
        "definition_index": 0,
        "uses": [
          {
            "constant_index": 0,
            "loading_unit_index": 0,
            "type": "constant"
          }
        ]
      }
    ]
  }
}

=== dwiilhammaulana/Project_UMKM_Solusion/.dart-home/Local/Pub/Cache/hosted/pub.dev/record_use-0.6.0/test_data/json/instance_duplicates.json
{
  "$schema": "../../doc/schema/record_use.schema.json",
  "constants": [
    {
      "type": "int",
      "value": 42
    },
    {
      "type": "int",
      "value": 43
    },
    {
      "definition_index": 0,
      "type": "instance",
      "value": {
        "i": 0
      }
    },
    {
      "definition_index": 0,
      "type": "instance",
      "value": {
        "i": 1
      }
    }
  ],
  "definitions": [
    {
      "path": [
        {
          "kind": "class",
          "name": "MyClass"
        }
      ],
      "uri": "package:record_use_test/instance_duplicates.dart"
    }
  ],
  "loading_units": [
    {
      "name": "1"
    }
  ],
  "uses": {
    "instances": [
      {
        "definition_index": 0,
        "uses": [
          {
            "constant_index": 2,
            "loading_unit_index": 0,
            "type": "constant"
          },
          {
            "constant_index": 3,
            "loading_unit_index": 0,
            "type": "constant"
          }
        ]
      }
    ]
  }
}
